config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :slots, only: [:index] do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/agent.rb
class Agent < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :slots, through: :bookings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :agent
  belongs_to :slot

  validates :agent_id, uniqueness: { scope: :slot_id }

  before_create :book_an_agent

  def book_an_agent
    slot = self.slot
    slot.nb_agent = slot.nb_agent - 1
    slot.save
  end
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :slots
  has_many :bookings, through: :slots

  def display_date
    I18n.l(self.date, format:'%a %d %B').capitalize()
  end 
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :day
  has_many :bookings

  validates :nb_agent, inclusion: { in: 0..100 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :booking
  has_one :agent
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @days = Day.all.order(date: :asc)
    @display_day = @days.first
    # Quand le champs est renseigné
    if params[:day].present?
      @display_day = Day.where(date: params[:day].to_date).first
    end
    @bookings = @display_day.bookings.where(agent_id: current_user.agent.id)
  end

  def create
    @booking = Booking.new()
    @slot = Slot.find(params[:slot_id])
    agents = Agent.all
    agent_availables = agents.select do |agent|
      !(agent.slots.where(id: @slot.id).length.positive?)
    end
    @booking.agent = agent_availables.sample
    @booking.slot = @slot
    @booking.user = current_user

    if @booking.save
      flash.alert = "Votre réservation est confirmée"
      redirect_to booking_path(@booking)
    else
      flash.alert = "Echec de la réservation"
      redirect_to slots_path
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    if user_signed_in?
      if current_user.agent.nil?
        # user is log in and is a client -> redirect to slots index
        redirect_to slots_path
      else
        # user is log in and is a agent -> redirect to bookings index
        redirect_to bookings_path
      end
    else
      # user is not log in
      redirect_to new_user_session_path
    end
  end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  def index
    if current_user.booking.nil?
      @days = Day.all.order(date: :asc)
      @display_day = @days.first
      # Quand le champs est renseigné
      if params[:day].present?
        @display_day = Day.where(date: params[:day].to_date).first
      end
    else
      redirect_to booking_path(current_user.booking)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="content">
  <br>
  <h1>Tableau de bord</h1>
  <% if @bookings.length == 0 %>
    <p>Vous n'avez pas de rendez vous ce jour</p>
  <% else %>
    <p>Vos rendez vous du <%= @display_day.display_date %> :</p>
    <div class="cards">
      <% @bookings.each do |booking| %>
        <div class="card">
          <p><%= booking.user.name %></p>
          <p>De <%= booking.slot.time_slot %></p>
        </div>
      <% end %>
    </div>
  <% end %>
  <hr>
  <%= form_with url: "/bookings", method: :get, local: true, class:"form-inline", :remote => true  do |form| %>
    <!-- Dropdown -->
    <div class="form-group">
      <%= form.select :day, @days.map {|day| [day.display_date, day.date]},
        {
          selected: "",
          prompt: 'Jour à venir',
        },
        {class: "form-control little-margin-bottom"} %>
    </div>
    <div class="form-group pt-2">
      <h3><%= form.submit "Chercher", class: "btn btn-flat-search" %></h3>
    </div>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="content">
  <br>
  <h3>Votre Rendez vous est confirmé avec : <%= @booking.agent.user.name %></h3>
  <h4>le <%= @booking.slot.day.date %> de <%= @booking.slot.time_slot %></h4>
  <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetingOrganizerRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    
    <div class="body">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="content">
    <div class="footer-content">
      <div class="footer-copyright">
        Any questions ? Suggestions ?
        <a href="mailto:negro.guillaume@gmail.com"><i class="fas fa-paper-plane"></i> Mail us</a>
      </div>
      <div class="footer-links">
        <a target="_blank" href="https://github.com/GN13008"><i class="fab fa-github"></i></a>
        <a target="_blank" href="https://www.linkedin.com/in/guillaumenegro/"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        Design by  <a target="_blank" href="https://gndevelopment.fr/"><i class="far fa-copyright"></i> GN Development</a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <% if user_signed_in? %>
      <p class="m-0">Bonjour <%= current_user.name %></p>
    <% end %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%# link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Se deconnecter", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <%# /users/sign_in to login %>
        <li class="nav-item">
          <%# <%= link_to "Schools", schools_path, class: "nav-link" %>
          <%# link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/slots/index.html.erb
<div class="content">
  <br>
  <h1>Voici les créneaux disponibles </h1>
  <br>
  <h3><%= @display_day.display_date %></h3>
  <hr>
  <div class="cards">
  <% @display_day.slots.where("nb_agent > 0").order(id: :asc).each do |slot| %>
    <div class="card">
      <p><%= slot.time_slot %></p>
      <p><%= link_to "Selectionner (#{slot.nb_agent})", slot_bookings_path(slot), method: :post %></p>
    </div>
  <% end %>
  </div>
  <hr>
  <%= form_with url: "/slots", method: :get, local: true, class:"form-inline", :remote => true  do |form| %>
    <!-- Dropdown -->
    <div class="form-group">
      <%= form.select :day, @days.map {|day| [day.display_date, day.date]},
        {
          selected: "",
          prompt: 'Changer de jour ?',
        },
        {class: "form-control little-margin-bottom"} %>
    </div>
    <div class="form-group pt-2">
      <h3><%= form.submit "Actualiser", class: "btn btn-flat-search" %></h3>
    </div>
  <% end %>
</div>